#ifndef __NX_CORE_H__
#define __NX_CORE_H__

#include <stdint.h>
#include <string.h>
#include <memory.h>
#include <malloc.h>

#define NX_INVALID_HANDLE 0

#define NX_FALSE 0
#define NX_TRUE 1

#define NX_ASSERT(x) if (!(x)) __debugbreak()

#define NX_NAME_MAX_SIZE 256

#define NX_MAX_WINDOWS 16
#define NX_MAX_GRAPHICS_CONTEXTS 16
#define NX_MAX_PHYSICAL_DEVICES 16
#define NX_MAX_SURFACES NX_MAX_WINDOWS
#define NX_MAX_LOGICAL_DEVICES 16
#define NX_MAX_SWAP_CHAINS 16
#define NX_MAX_IMAGES 512
#define NX_MAX_IMAGE_VIEWS 512
#define NX_MAX_COMMAND_POOLS 16
#define NX_MAX_COMMAND_BUFFERS 64

#define NX_DEFAULT_OFFSET 1024
#define NX_WINDOW_OFFSET NX_DEFAULT_OFFSET
#define NX_GRAPHICS_CONTEXT_OFFSET (NX_WINDOW_OFFSET + NX_MAX_WINDOWS)
#define NX_PHYSICAL_DEVICE_OFFSET (NX_GRAPHICS_CONTEXT_OFFSET + NX_MAX_GRAPHICS_CONTEXTS)
#define NX_SURFACE_OFFSET (NX_PHYSICAL_DEVICE_OFFSET + NX_MAX_PHYSICAL_DEVICES)
#define NX_LOGICAL_DEVIC_OFFSET (NX_SURFACE_OFFSET + NX_MAX_SURFACES)
#define NX_SWAP_CHAIN_OFFSET (NX_LOGICAL_DEVIC_OFFSET + NX_MAX_LOGICAL_DEVICES)
#define NX_IMAGE_OFFSET (NX_SWAP_CHAIN_OFFSET + NX_MAX_SWAP_CHAINS)
#define NX_IMAGE_VIEW_OFFSET (NX_IMAGE_OFFSET + NX_MAX_IMAGES)
#define NX_COMMAND_POOL_OFFSET (NX_IMAGE_VIEW_OFFSET + NX_MAX_IMAGE_VIEWS)
#define NX_COMMAND_BUFFER_OFFSET (NX_COMMAND_POOL_OFFSET + NX_MAX_COMMAND_POOLS)

typedef uint32_t nxHandle;

#endif // __NX_CORE_H__